# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff13c4ecefb52d0312c7606d73e2a4fbc68f67d5eb153e9cd619a93832bce27b92e193dea1acbcf209b535953123370252319c877c852472447e8a21c369a382

test:
  secret_key_base: d8fb81f3549a0303ed27f857d6c915ccf7b8de3f775ddc9954a7eddb42d38c207344fe8607f6f438f577416a70bd836a6dc619792c406452ce2967dba0f3c70f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
